[workspace]
members = [
  "helix-core",
  "helix-view",
  "helix-term",
  "helix-tui",
  "helix-lsp",
  "helix-dap",
  "xtask",
]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
lto = "thin"
# debug = true
